function GM.MakeChangeLogs()
	surface.PlaySound("buttons/lightswitch2.wav")
	if IsValid(tea_ChangeLogsFrame) then tea_ChangeLogsFrame:Remove() end

	local wide,tall = 920,660
	tea_ChangeLogsFrame = vgui.Create( "DFrame" )
	tea_ChangeLogsFrame:SetSize(wide, tall)
	tea_ChangeLogsFrame:Center()
	tea_ChangeLogsFrame:SetTitle ("")
	tea_ChangeLogsFrame:SetDraggable(false)
	tea_ChangeLogsFrame:SetVisible( true )
	tea_ChangeLogsFrame:SetAlpha(0)
	tea_ChangeLogsFrame:AlphaTo(255, 0.25, 0)
	tea_ChangeLogsFrame:ShowCloseButton(true)
	tea_ChangeLogsFrame:MakePopup()
	tea_ChangeLogsFrame.Paint = function()
		draw.RoundedBox(2, 0, 0, tea_ChangeLogsFrame:GetWide(), tea_ChangeLogsFrame:GetTall(), Color(0, 0, 0, 200))
		surface.SetDrawColor(150, 150, 0 ,255)
		surface.DrawOutlinedRect(0, 0, tea_ChangeLogsFrame:GetWide(), tea_ChangeLogsFrame:GetTall())
	end

	local text = vgui.Create("DLabel", tea_ChangeLogsFrame)
	text:SetPos(12, 4)
	text:SetFont("TargetID")
	text:SetText(Format("Newest update: %s", GAMEMODE.Version))
	text:SizeToContents()

	local list = vgui.Create("DPanelList", tea_ChangeLogsFrame)
	list:EnableVerticalScrollbar()
	list:EnableHorizontal(false)
	list:SetSize(wide - 20, tall - 40)
	list:SetPos(12, 32)
	list:SetPadding(8)
	list:SetSpacing(4)

	gamemode.Call("AddExtraOptions", list, tea_ChangeLogsFrame)

---- Help about changelogs info
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "Help about changelogs: (Note: Some may not be accurate)", "TargetID", Color(255,255,255)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ means something is added", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "- means something is removed", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+- means something is added and something similar is removed", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "; means something is reworked", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "/ means something is changed", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= means something got balance changed", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "* means something is fixed", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "? means other unknown changes/fixes\n\n", "TargetIDSmall", Color(205,205,205)))


	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "v0.11.0 [BETA B], 17 November 2022\n", "TargetID", Color(255,255,255)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added new convar that allows to set death sound volume", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added Changelogs panel\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "; Reworked death sound (sound now fades out on respawn)\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "/ Changed WIP button in context menu to changelogs\n\n", "TargetIDSmall", Color(205,205,205)))

	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "v0.11.0 [BETA A], 16 November 2022\n", "TargetID", Color(255,255,255)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added ATE sweps pack into gamemode files", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added AR2 Combine Pistol & Rifle weapons", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added AWM the AWP and Steyr AUG A1 weapons from MAD Cows", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added back some ATE weapons", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added new ConVars (no achievements yet)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ New rarity text & color format (in inventory, trader, etc., colors vary on rarity)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added Options Menu (F4)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ System can now forget the last attacker if target didn't take damage within last 15 seconds", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added function to add invalid items to invalid inventory and vice versa", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added Environmental Protection (protects from environment damage)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Crafting System finally added (it is functional right?)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ New Admin Command (no, this is JUST available to dev and the command can change convar values)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ New Loot Type: Rare Loot Cache", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added Death sounds", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added new Auto-Maintenance system (server auto-restart if it's up for a long time)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ New Zombie Boss", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ More debug modes (WIP)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "+ Added configurable door health\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "- Removed Cokctail Molotov from inventory (that thing can cause server crashes)\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "; Reworked zombie destroying doors (now they deal damage to them instead of destroying them instantly)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "; Tyrant can now break doors and props", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "; Changed some panels to close instead of remove", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "; New damage calculating functions\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "/ Tweaked Zombie Stats", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "/ Zombie now damage props and doors more often", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "/ Renamed Health skill to Vitality", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "/ Changed most of panels' outlines from red to yellow\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Nerfed Minigun accuracy", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Decreased The Fuckinator's damage (1000 => 800)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Decreased FN Scar firerate, increased Damage", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Decreased The Punisher damage (150 => 145)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Increased Bosch-Sterling B-60 damage (20 => 21)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Increased Blackhawk sniper damage (85 => 87)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Increased cooldown between usages for ammo pile (30sec => 40sec)", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Removed The Fuckinator from faction loot caches, airdrop faction LootTable and added to airdrop special LootTable", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "= Rebalanced M9K guns cost\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "* Fixed PvP Guarded mode giving players PvP toggling cooldown, if player with pvp enabled has damaged them\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "? And More changes i don't even know ?\n\n\n", "TargetIDSmall", Color(205,205,205)))
	list:AddItem(EasyLabel(tea_ChangeLogsFrame, "INFORMATION: I will add more changelogs soon, stay tuned.", "TargetIDSmall", Color(205,205,205)))


end
