function GM:MakeChangeLogs()
	surface.PlaySound("buttons/lightswitch2.wav")
	if IsValid(self.ChangeLogsFrame) then self.ChangeLogsFrame:Remove() end

	local wide,tall = 920,660
	self.ChangeLogsFrame = vgui.Create( "DFrame" )
	self.ChangeLogsFrame:SetSize(wide, tall)
	self.ChangeLogsFrame:Center()
	self.ChangeLogsFrame:SetTitle ("")
	self.ChangeLogsFrame:SetDraggable(false)
	self.ChangeLogsFrame:SetVisible( true )
	self.ChangeLogsFrame:SetAlpha(0)
	self.ChangeLogsFrame:AlphaTo(255, 0.25, 0)
	self.ChangeLogsFrame:ShowCloseButton(true)
	self.ChangeLogsFrame:MakePopup()
	self.ChangeLogsFrame.Paint = function()
		draw.RoundedBox(2, 0, 0, self.ChangeLogsFrame:GetWide(), self.ChangeLogsFrame:GetTall(), Color(0, 0, 0, 200))
		surface.SetDrawColor(150, 150, 0 ,255)
		surface.DrawOutlinedRect(0, 0, self.ChangeLogsFrame:GetWide(), self.ChangeLogsFrame:GetTall())
	end

	local text = vgui.Create("DLabel", self.ChangeLogsFrame)
	text:SetPos(12, 4)
	text:SetFont("TargetID")
	text:SetText(Format("Newest update: %s", self.Version))
	text:SizeToContents()

	local list = vgui.Create("DPanelList", self.ChangeLogsFrame)
	list:EnableVerticalScrollbar()
	list:EnableHorizontal(false)
	list:SetSize(wide - 20, tall - 40)
	list:SetPos(12, 32)
	list:SetPadding(8)
	list:SetSpacing(4)

	gamemode.Call("AddExtraOptions", list, self.ChangeLogsFrame)

	local function MakeText(panel, text, font, color)
		return EasyLabel(panel, text, font, color or Color(205,205,205))
	end

---- Help about changelogs info
---- No. there won't be any translations for changelogs.
	list:AddItem(MakeText(self.ChangeLogsFrame, "Help about changelogs: (Note: Some may not be accurate)", "TargetID", Color(255,255,255)))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ added", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "- removed", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+- added and something similar is removed", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; reworked", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ changed", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= balance change", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "* fixed", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "? other unknown changes/fixes\n\n", "TargetIDSmall"))

	list:AddItem(MakeText(self.ChangeLogsFrame, "v0.11.1, 07 April 2023\n", "TargetID", Color(255,255,255)))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New weapons and items", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Tasks", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; Strength skill (added melee damage)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; Renamed Damage skill to Gunslinger and reworked", "TargetIDSmall"))

/*
	list:AddItem(MakeText(self.ChangeLogsFrame, "v0.11.0 [BETA C], ?? November 2022\n", "TargetID", Color(255,255,255)))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New convar that allows to set death sound volume", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Changelogs panel\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; Reworked death sound (sound now fades out on respawn)\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ WIP button in context menu to changelogs\n\n", "TargetIDSmall"))

	list:AddItem(MakeText(self.ChangeLogsFrame, "v0.11.0 [BETA B], 17 November 2022\n", "TargetID", Color(255,255,255)))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New convar that allows to set death sound volume", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Changelogs panel\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; Reworked death sound (sound now fades out on respawn)\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ WIP button in context menu to changelogs\n\n", "TargetIDSmall"))

	list:AddItem(MakeText(self.ChangeLogsFrame, "v0.11.0 [BETA A], 16 November 2022\n", "TargetID", Color(255,255,255)))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ ATE sweps pack into gamemode files", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ AR2 Combine Pistol & Rifle weapons", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ AWM the AWP and Steyr AUG A1 weapons from MAD Cows", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Back some ATE weapons", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New ConVars (no achievements yet)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New rarity text & color format (in inventory, trader, etc., colors vary on rarity)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Options Menu (F4)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ System can now forget the last attacker if target didn't take damage within last 15 seconds", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Function to add invalid items to invalid inventory and vice versa", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Environmental Protection (protects from environment damage)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Crafting System finally added (it is functional right?)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New Admin Command (no, this is JUST available to dev and the command can change convar values)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New Loot Type: Rare Loot Cache", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Death sounds", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New Auto-Maintenance system (server auto-restart if it's up for a long time)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ New Zombie Boss", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ More debug modes (WIP)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "+ Configurable door health\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "- Cocktail Molotov from items list (that thing can cause server crashes)\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; Reworked zombie destroying doors (now they deal damage to them instead of destroying them instantly)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; Tyrant can now break doors and props", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "; New damage calculating functions\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ Changed some panels to close instead of remove", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ Tweaked Zombie Stats", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ Zombie now damage props and doors more often", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ Renamed Health skill to Vitality", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "/ Most of panels' outlines from red to yellow\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Nerfed Minigun accuracy", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Decreased The Fuckinator's damage (1000 => 800)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Decreased FN Scar firerate, increased Damage", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Decreased The Punisher damage (150 => 145)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Increased Bosch-Sterling B-60 damage (20 => 21)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Increased Blackhawk sniper damage (85 => 87)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Increased cooldown between usages for ammo pile (30sec => 40sec)", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Removed The Fuckinator from faction loot caches, airdrop faction LootTable and added to airdrop special LootTable", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "= Rebalanced M9K guns cost\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "* PvP Guarded mode giving players PvP toggling cooldown, if player with pvp enabled has damaged them\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "? And More changes i don't even know ?\n\n\n", "TargetIDSmall"))
	list:AddItem(MakeText(self.ChangeLogsFrame, "INFORMATION: I will add more changelogs soon, stay tuned.", "TargetIDSmall"))
*/

end
