TEAM_LONER = 1

-- Item categories and Item types are different

ITEMCATEGORY_AMMO = 1
ITEMCATEGORY_SUPPLIES = 2
ITEMCATEGORY_WEAPONS = 3
ITEMCATEGORY_ARMOR = 4
ITEMCATEGORY_JUNK = 5
ITEMCATEGORY_MISCELLANEOUS = 6
ITEMCATEGORY_ARMORATT = 7
ITEMCATEGORY_SPECIAL = 8

ITEMTYPE_AMMO = 1
ITEMTYPE_MED = 2
ITEMTYPE_MEDANTIDOTE = 3
ITEMTYPE_FOOD = 4
ITEMTYPE_DRINK = 5
ITEMTYPE_WEAPON = 6
ITEMTYPE_GRENADE = 7
ITEMTYPE_ARMOR = 8
ITEMTYPE_ARMORATT = 9
ITEMTYPE_OTHER = 10

HUDSTYLE_ATE = 0
HUDSTYLE_CLASSIC = 1
HUDSTYLE_TEA = 2

SEASONAL_EVENT_NONE = 0
SEASONAL_EVENT_EASTER = 1
SEASONAL_EVENT_HALLOWEEN = 2
SEASONAL_EVENT_CHRISTMAS = 3

EVENT_NONE = 0
EVENT_ZOMBIEAPOCALYPSE = 1

DEBUGGING_NONE = 0
DEBUGGING_NORMAL = 1
DEBUGGING_ADVANCED = 2

TIME_SECOND = 1
TIME_MINUTE = 60
TIME_HOUR = 3600
TIME_DAY = 86400
TIME_WEEK = TIME_DAY * 7
TIME_YEAR = TIME_DAY * 365

-- pretty much unused
--[[
SKILL_AGILITY = 1
SKILL_BARTER = 2
SKILL_DAMAGE = 3
SKILL_DEFENSE = 4
SKILL_ENDURANCE = 5
SKILL_ENGINEER = 6
SKILL_IMMUNITY = 7
SKILL_KNOWLEDGE = 8
SKILL_MEDSKILL = 9
SKILL_SALVAGE = 10
SKILL_SPEED = 11
SKILL_STRENGTH = 12
SKILL_SURVIVOR = 13
SKILL_VITALITY = 14
]]

RARITY_TRASH = 0
RARITY_JUNK = 1
RARITY_COMMON = 2
RARITY_UNCOMMON = 3
RARITY_RARE = 4
RARITY_SUPERRARE = 5
RARITY_EPIC = 6
RARITY_LEGENDARY = 7
RARITY_MYTHIC = 8
RARITY_GODLY = 9
RARITY_EVENT = 10
RARITY_UNOBTAINABLE = 11

VARIANT_POISONOUS = 1
VARIANT_SHOCK = 2
VARIANT_OVERPOWERED = 3
VARIANT_REFLECTOR = 4
VARIANT_INFECTIVE = 5
VARIANT_SICKNESS = 6
VARIANT_LEECH = 7
VARIANT_ENRAGED = 8

WEIGHT_UNIT = "kg"

GM.VariantNames = {
    [VARIANT_POISONOUS] = "Poisonous",
    [VARIANT_SHOCK] = "Shock",
    [VARIANT_OVERPOWERED] = "Overpowered",
    [VARIANT_REFLECTOR] = "Reflector",
    [VARIANT_INFECTIVE] = "Infective",
    [VARIANT_SICKNESS] = "Sickness",
    [VARIANT_LEECH] = "Leech",
    [VARIANT_ENRAGED] = "Enraged"
}

GM.ItemTypes = {
    [ITEMTYPE_AMMO] = "Ammo",
    [ITEMTYPE_MED] = "Medical Item",
    [ITEMTYPE_MEDANTIDOTE] = "Antidote",
    [ITEMTYPE_FOOD] = "Food",
    [ITEMTYPE_DRINK] = "Drink",
    [ITEMTYPE_WEAPON] = "Weapon",
    [ITEMTYPE_GRENADE] = "Grenade",
    [ITEMTYPE_ARMOR] = "Armor",
    [ITEMTYPE_ARMORATT] = "Armor Attachment",
    [ITEMTYPE_OTHER] = "Other",
}

DIFFICULTY_GAMEPLAY_BASIC = 1
DIFFICULTY_GAMEPLAY_NORMAL = 2
DIFFICULTY_GAMEPLAY_ADVANCED = 3
DIFFICULTY_GAMEPLAY_CHALLENGING = 4
DIFFICULTY_GAMEPLAY_ULTIMATE = 5
DIFFICULTY_GAMEPLAY_HELL = 5
DIFFICULTY_GAMEPLAY_IMPOSSIBLE = 6

DIFFICULTY_ECONOMY_EASY = 1
DIFFICULTY_ECONOMY_STANDARD = 2
DIFFICULTY_ECONOMY_DIFFICULT = 3
DIFFICULTY_ECONOMY_COMPLEX = 4
DIFFICULTY_ECONOMY_HARSH = 5
DIFFICULTY_ECONOMY_HELLISH = 6

DIFFICULTY_INFLATION_OFF = 0
DIFFICULTY_INFLATION_LOW = 1
DIFFICULTY_INFLATION_MEDIUM = 2
DIFFICULTY_INFLATION_NORMAL = 3
DIFFICULTY_INFLATION_INTERMEDIATE = 4
DIFFICULTY_INFLATION_HIGH = 5
DIFFICULTY_INFLATION_VERYHIGH = 6
DIFFICULTY_INFLATION_WORLDCRISIS = 7


OPENWORLD_NETTYPE_SENDINFO = 1
OPENWORLD_NETTYPE_CANCEL = 2
OPENWORLD_NETTYPE_CONFIRM = 3
OPENWORLD_NETTYPE_SENDMAPSINFO = 4
OPENWORLD_NETTYPE_LEFTAREA = 5
OPENWORLD_NETTYPE_UPDATEPLAYERS = 6
OPENWORLD_NETTYPE_CLEANUPTRANSITIONS = 7
OPENWORLD_NETTYPE_CLEANUPALLTRANSITIONS = 8
OPENWORLD_NETTYPE_EDITTRANSITION = 9
OPENWORLD_NETTYPE_DELTRANSITION = 10
OPENWORLD_NETTYPE_GETTRANSITIONSINFO = 11 -- admin only

ADMINTOOL_MODE_SPAWNER = 1
ADMINTOOL_MODE_DELETE = 2
ADMINTOOL_MODE_DELETEUNSAFE = 3

ADMINTOOL_SPAWNTYPE_ZOMBIE = 1
ADMINTOOL_SPAWNTYPE_PROPSFLIMSY = 2
ADMINTOOL_SPAWNTYPE_PROPSSTRONG = 3
ADMINTOOL_SPAWNTYPE_FACSTRUCTURES = 4
ADMINTOOL_SPAWNTYPE_MAPSPAWNS = 5
ADMINTOOL_SPAWNTYPE_TOOL = 6

--- ↓ Do. Not. Touch. ↓
--- It's not even implemented yet. ---

GM.PlayerCharactersTest = false
